[build]
  command = "npm ci && npm run build"
  publish = "dist"

[[headers]]
  for = "/trello-connector.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

[[headers]]
  for = "/powerup.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

[[headers]]
  for = "/app.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
